# Generated by Django 4.2.6 on 2023-10-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
