# Generated by Django 4.2.6 on 2023-10-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_team_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
