# Generated by Django 4.2.6 on 2023-10-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='password',
        ),
        migrations.AddField(
            model_name='team',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
