# Generated by Django 4.2.6 on 2023-10-27 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0007_remove_note_password_team_password_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='admin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
